name: opti-de-redes
channels:
  - conda-forge
  - gurobi
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - pandas
  - scipy
  - gurobipy
  - cobra
  - wcwidth
  - jupyter
  - ipykernel
  - seaborn